export const DARAGA_BARANGAYS = [
  'Alcala',
  'Alobo',
  'Anislag',
  'Bagumbayan',
  'Balinad',
  'Bañadero',
  'Bañag',
  'Bascaran',
  'Bigao',
  'Binitayan',
  'Bongalon',
  'Budiao',
  'Burgos',
  'Busay',
  'Canarom',
  'Cullat',
  'Dela Paz',
  'Dinoronan',
  'Gabawan',
  'Gapo',
  'Ibaugan',
  'Ilawod Area Pob.',
  'Inarado',
  'Kidaco',
  'Kilicao',
  'Kimantong',
  'Kinawitan',
  'Kiwalo',
  'Lacag',
  'Mabini',
  'Malabog',
  'Malobago',
  'Maopi',
  'Market Area Pob.',
  'Maroroy',
  'Matnog',
  'Mayon',
  'Mi-isi',
  'Nabasan',
  'Namantao',
  'Pandan',
  'Peñafrancia',
  'Sagpon',
  'Salvacion',
  'San Rafael',
  'San Ramon',
  'San Roque',
  'San Vicente Grande',
  'San Vicente Pequeño',
  'Sipi',
  'Tabon-tabon',
  'Tagas',
  'Talahib',
  'Villahermosa',
] as const

export type DaragaBarangay = (typeof DARAGA_BARANGAYS)[number]

export function isDaragaBarangay(value: string): value is DaragaBarangay {
  return DARAGA_BARANGAYS.includes(value as DaragaBarangay)
}
